### ISSUE TITLE
Módulos de sobra

### ISSUE THREAD

**Issue by fede2cr** [greencorecr/SIGUCA#8]
Revisando algunos de los mensajes sobre libería obsoletas a la hora de instalar las librerías requeridas, noto que algunas de las librerías que están incluídas podrían no estarse usando.

Un ejemplo creo que sería la librería de moccha, de la cual no parece tener algún test.js asociado por lo que parece que se incluyó prematuramente. Favor revisar con las otras que aparecen.

De forma similar, revisar que las librerías que piden una versión específica no funcionarían con "latest".

De forma similar se cambió "jade" por "pug" y parece estar funcionando sin problemas. Se recomienda el mismo cambio para el branch en desarrollo.

**Comment by fede2cr** [comment]
Similar a moccha, también parece que se puede eliminar "chai".

**Comment by bfhg17** [comment]
Buenas Tardes , Gracias por las revisiones que me ha brindado con respecto al proyecto , voy a comenzar a tratarlas, cualquier otra consideración no dude en notificármelo!
-B.H

**Comment by bfhg17** [comment]
- Al parecer todas las dependencias  pueden llamarse con lastest, con la excepción de Express, que necesita la **3.1.0**, si no lanza un excepción ,al parecer la versión latest de express según he investigado ya no trae empaquetado en conjunto **compress**, ahora se llama  **compression**,habría que ejecutarlo e instalarlo por separado para implementarlo ,Además de  cambiar las instancias  a ver si las soporta , de primera mano haciendo pruebas al declararla sobre .config/express.js no tuve buenos resultados de funcionalidad continuaba con la excepción, sin embargo no sé que le parece a usted si será necesario el upgrade o nos quedamos sobre 3.1.0?
- También descarte dentro del package.json  de mi instancia las dependencias de moccha y chai ,y hasta el momento no he tenido ningún inconveniente.
-  Con respecto a pug como usted lo comentaba no he tenido ningún  problema tampoco.

Gracias!
-B.H

**Comment by fede2cr** [comment]
Creo que por la migración a express4 ser un poco más larga, podría manejarse en un branch aparte.
Con el resto de cosas, excelente.
